# Generated by Django 6.1 on 2026-08-09 12:51

from django.db import migrations
from django.utils import timezone

def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()
    if User.objects.exists():
        return

    superuser = User.objects.create_superuser(
        username="Shakti",
        email="luna.milaba@gmail.com",
        password="ShAkTi2026AL",
        last_login=timezone.now()
    )
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
